stages:
  - test
  - build
  - deploy

test:
  image: python:3.8
  stage: test
  script:
    - pip install flake8
    - flake8 api_rest

build:
  image: docker:24.0.3
  stage: build
  services:
    - docker:24.0.3-dind
  variables:
    LATEST_IMAGE: $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $LATEST_IMAGE || true
    - docker build --network host --cache-from $LATEST_IMAGE -t $LATEST_IMAGE .
    - docker push $LATEST_IMAGE

deploy:
  image:
    name: lachlanevenson/k8s-kubectl:latest
    entrypoint: [""]
  stage: deploy
  only:
    - main
  before_script:
    - apk add --no-cache gettext
    - echo $KUBERNETES_HOME | base64 -d > kubeconfig.txt
    - export KUBECONFIG=$(pwd)/kubeconfig.txt
    - export IMAGE=$CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:latest
  script:
    - |
      kubectl --namespace=$KUBERNETES_NAMESPACE create secret docker-registry gitlab-read-registry \
        --docker-server=registry.forge.hefr.ch \
        --docker-username="gitlab-read-registry" \
        --docker-password="$(echo -n $REGISTRY_ACCESS_TOKEN_PASSWORD | base64 -d)" \
        -o yaml --save-config --dry-run=client | kubectl apply -f -  
    - envsubst < api_rest/deploy.yaml | kubectl apply --namespace=$KUBERNETES_NAMESPACE -f -